'use client';
import { useMemo, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { formatPrice } from '@/lib/format-price';
import { cartSubtotal, itemTotal, useCart } from '@/stores/cart-store';
import { useToastStore } from '@/stores/toast-store';
export function CartPageContent(){
  const {items,increment,decrement,removeItem}=useCart(); const showToast=useToastStore((state)=>state.show); const [code,setCode]=useState(''); const [discounted,setDiscounted]=useState(false); const [error,setError]=useState('');
  const subtotal=cartSubtotal(items); const delivery=items.length?49000:0; const discount=discounted?Math.round(subtotal*.1):0; const total=useMemo(()=>subtotal+delivery-discount,[subtotal,delivery,discount]);
  const applyCode=()=>{if(code.trim().toUpperCase()==='KABAB10'){setDiscounted(true);setError('');showToast('تخفیف ۱۰ درصدی اعمال شد')}else{setDiscounted(false);setError('کد واردشده معتبر نیست')}};
  if(!items.length)return <div className="empty-cart page-empty"><ShoppingBag/><h2>سبد خرید شما خالی است</h2><p>از منوی امروز یک غذای خوش‌طعم انتخاب کنید.</p><Link href="/menu" className="primary-button">مشاهده منو</Link></div>;
  return <div className="cart-page-grid"><section className="cart-list"><h2>اقلام سفارش</h2>{items.map((item)=><article key={item.key}><div className="cart-item-image"><Image src={item.food.image} alt={item.food.title} fill sizes="110px"/></div><div><h3>{item.food.title}</h3><p>{item.addons.map((addon)=>addon.title).join('، ')||item.food.shortDescription}</p>{item.note&&<p>یادداشت: {item.note}</p>}<strong>{formatPrice(itemTotal(item))}</strong></div><div className="qty"><button type="button" onClick={()=>decrement(item.key)} disabled={item.quantity===1} aria-label={`کم کردن ${item.food.title}`}><Minus/></button><span>{item.quantity.toLocaleString('fa-IR')}</span><button type="button" onClick={()=>increment(item.key)} aria-label={`زیاد کردن ${item.food.title}`}><Plus/></button></div><button type="button" className="remove" onClick={()=>removeItem(item.key)} aria-label={`حذف ${item.food.title}`}><Trash2/></button></article>)}</section><aside className="order-summary"><h2>خلاصه سفارش</h2><label htmlFor="discount"><span>کد تخفیف <small>KABAB10</small></span></label><div className="discount-field"><input id="discount" value={code} onChange={(event)=>setCode(event.target.value)} placeholder="کد خود را وارد کنید"/><button type="button" onClick={applyCode}>اعمال</button></div>{error&&<p className="field-error" role="alert">{error}</p>}<dl><div><dt>جمع سفارش</dt><dd>{formatPrice(subtotal)}</dd></div><div><dt>هزینه ارسال تقریبی</dt><dd>{formatPrice(delivery)}</dd></div><div><dt>تخفیف</dt><dd>{discount?`− ${formatPrice(discount)}`:'۰ تومان'}</dd></div></dl><div className="summary-total"><span>مبلغ نهایی</span><strong>{formatPrice(total)}</strong></div><Link href="/checkout" className="primary-button">ادامه و ثبت سفارش</Link><small>هزینه نهایی با انتخاب نحوه دریافت به‌روز می‌شود.</small></aside></div>;
}
