import Link from 'next/link';
import { ArrowLeft, Camera as Instagram, Clock3, Leaf, MapPin, PackageCheck, Soup, Sparkles, Truck } from 'lucide-react';
import { FoodCard } from '@/components/menu/food-card';
import { foods } from '@/data/foods';
const categoryCards=[['کباب‌ها','۷ مدل',foods[0].image],['جوجه‌ها','۴ مدل',foods[2].image],['چلوها','۵ مدل',foods[7].image],['خورشت‌ها','۳ مدل',foods[9].image]];
const photoShowcase=[foods[4],foods[2],foods[8],foods[0],foods[9],foods[11]];
export default function Home(){return <main>
  <section className="hero"><div className="container hero-layout"><div className="hero-copy"><span className="eyebrow"><i/>از روی آتش، مستقیم برای شما</span><h1>کباب داغ،<br/><em>برنج ایرانی</em></h1><p>طعمی آشنا از گوشت تازه، زعفران ایرانی و پخت روزانه؛ همان غذایی که با خیال راحت برای خانواده سفارش می‌دهید.</p><div className="hero-buttons"><Link className="primary-button" href="/menu">سفارش آنلاین <ArrowLeft/></Link><Link className="ghost-button" href="/menu">دیدن منوی امروز</Link></div><div className="hero-facts"><span><strong>۳۵–۴۵</strong><small>دقیقه تا تحویل</small></span><span><strong>۱۵+</strong><small>سال تجربه</small></span><span><strong>هر روز</strong><small>پخت تازه</small></span></div></div><div className="hero-visual"><div className="hero-image" role="img" aria-label="چلوکباب تازه با برنج زعفرانی"/><div className="hero-photo-card"><span>پیشنهاد امروز</span><strong>چلوکباب سلطانی</strong></div><div className="hero-location"><MapPin/><span><small>ارسال از شعبه</small><strong>تهران</strong></span></div></div></div></section>
  <section className="section container"><div className="section-heading"><div><span>انتخاب‌های محبوب</span><h2>پرفروش‌ترین‌ها</h2><p>محبوب‌ترین انتخاب‌های مشتریان خانه کباب طهران</p></div><Link href="/menu">مشاهده همه <ArrowLeft/></Link></div><div className="food-grid">{foods.filter(f=>f.featured).slice(0,6).map(f=><FoodCard key={f.id} food={f}/>)}</div></section>
  <section className="photo-showcase"><div className="container"><div className="photo-showcase-copy"><span>تازه از روی آتش</span><h2>هر قاب، یک طعم اصیل</h2><p>تصویرهای واقعی غذاها به‌زودی جایگزین می‌شوند تا همان چیزی را ببینید که تحویل می‌گیرید.</p></div><div className="photo-mosaic">{photoShowcase.map((food,index)=><Link href={`/menu/${food.slug}`} key={`${food.id}-${index}`} className={`photo-tile tile-${index+1}`} style={{backgroundImage:`url(${food.image})`}}><span>{food.title}</span></Link>)}</div></div></section>
  <section className="category-section"><div className="container"><div className="center-heading"><span>منوی امروز</span><h2>چی میل دارید؟</h2></div><div className="category-grid">{categoryCards.map(c=><Link href="/menu" className="category-card" key={c[0]} style={{backgroundImage:`url(${c[2]})`}}><span><strong>{c[0]}</strong><small>{c[1]}</small></span><ArrowLeft/></Link>)}</div></div></section>
  <section className="container offer"><div className="offer-image"/><div className="offer-copy"><span>پیشنهاد ویژه خانه کباب</span><h2>پک دو نفره کباب</h2><p>دو پرس چلوکباب کوبیده، سالاد شیرازی و دوغ سنتی</p><div className="offer-price"><del>۸۲۰٬۰۰۰</del><strong>۷۲۹٬۰۰۰ <small>تومان</small></strong></div><Link href="/menu" className="primary-button">سفارش پک <ArrowLeft/></Link></div></section>
  <section id="about" className="about section"><div className="container about-grid"><div className="about-image"><div className="experience"><strong>۱۵+</strong><span>سال طعم<br/>و خاطره</span></div></div><div><span className="red-label">داستان ما</span><h2>خانه کباب طهران؛<br/>طعم آشنای غذای ایرانی</h2><p>از مواد اولیه تازه تا پخت روزانه؛ هر بشقاب با دقت، تجربه و احترام به دستورهای اصیل ایرانی آماده می‌شود.</p><ul className="about-list"><li><Leaf/><span><strong>مواد اولیه منتخب</strong><small>خرید روزانه و کنترل کیفیت</small></span></li><li><Soup/><span><strong>دستور اصیل ایرانی</strong><small>طعمی آشنا، تازه و صمیمی</small></span></li></ul></div></div></section>
  <section className="why container section"><div className="center-heading"><span>چرا ما؟</span><h2>سفارش شما، گرم و تازه</h2></div><div className="feature-grid">{[[Sparkles,'طعم اصیل','مزه‌ای از دل آشپزخانه ایرانی'],[Leaf,'مواد اولیه تازه','انتخاب روزانه و باکیفیت'],[PackageCheck,'بسته‌بندی مناسب','حفظ کیفیت تا در خانه'],[Truck,'ارسال سریع','تحویل گرم و به‌موقع']].map(([Icon,t,d])=><article key={String(t)}><Icon/><h3>{String(t)}</h3><p>{String(d)}</p></article>)}</div></section>
  <section className="instagram-section"><div className="container"><div className="section-heading"><div><span><Instagram/> خانه کباب در اینستاگرام</span><h2 dir="ltr">@Khane-kabab-tehran</h2></div><a href="https://instagram.com/Khane-kabab-tehran">دنبال کنید <ArrowLeft/></a></div><div className="insta-grid">{foods.slice(0,5).map(f=><div key={f.id} style={{backgroundImage:`url(${f.image})`}}><Instagram/></div>)}</div></div></section>
  <section className="final-cta"><div className="container"><Clock3/><div><h2>غذای امروزت رو انتخاب کردی؟</h2><p>تازه از آشپزخانه، مستقیم تا در خانه شما</p></div><Link href="/menu" className="primary-button">مشاهده منو <ArrowLeft/></Link></div></section>
  </main>}
